name: sqflite_live
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <4.0.0'
flutter:
  assets:
    - sqlite_viewer/package.zip
# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  sqflite: '>=2.2.0 <3.0.0'
  path_provider: '>=2.0.0 <3.0.0'
  equatable: '>=2.0.0 <3.0.0'
  shelf: ^1.4.2
  shelf_static: ^1.1.3
  logger: '>=2.0.0 <3.0.0'
  path: '>=1.8.1 <2.0.0'
  archive: '>=3.3.0 <5.0.0'
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
