name: sqflite_live
description: Sqflite live server for viewing db data on web-based local server.
version: 1.2.1

environment:
  sdk: ^3.0.0
repository: https://github.com/nemr0/sqflite_live
flutter:
  assets:
    - sqlite_viewer/
    - sqlite_viewer/css/
    - sqlite_viewer/img/
    - sqlite_viewer/js/
    - sqlite_viewer/js/ace/
# Add regular dependencies here.
dependencies:
  sqflite: ^2.4.3
  path_provider: ^2.1.6
  path: ^1.9.1
  mime: ^2.0.0
  flutter:
    sdk: flutter
dev_dependencies:
  lints: ^6.0.0
  test: ^1.31.0
  flutter_test:
    sdk: flutter
