name: sqflite_live
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  sqflite: '>=2.0.0 <3.0.0'
  path_provider: '>=2.0.0 <3.0.0'
  equatable: '>=2.0.0 <3.0.0'
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
